/*
 * main.c - Initialization and command line interface
 *
 * de Jong Explorer - interactive exploration of the Peter de Jong attractor
 * Copyright (C) 2004 David Trowbridge and Micah Dowty
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 */

#include <gtk/gtk.h>
#include <stdlib.h>
#include <time.h>
#include <getopt.h>
#include "de-jong.h"
#include "explorer.h"

static void usage(char **argv);
static void render_main(DeJong *dejong, const gchar *filename);


int main(int argc, char ** argv) {
  DeJong* dejong;
  enum {INTERACTIVE, RENDER} mode = INTERACTIVE;
  const gchar *outputFile;
  int c, option_index=0;

  srand(time(NULL));
  g_type_init();

  dejong = de_jong_new();

  while (1) {
    static struct option long_options[] = {
      {"help",        0, NULL, 'h'},
      {"read",        1, NULL, 'i'},
      {"output",      1, NULL, 'o'},
      {"zoom",        1, NULL, 'z'},
      {"rotation",    1, NULL, 'r'},
      {"blur-radius", 1, NULL, 1000},
      {"blur-ratio",  1, NULL, 1001},
      {"exposure",    1, NULL, 'e'},
      {"gamma",       1, NULL, 'g'},
      {"foreground",  1, NULL, 1002},
      {"background",  1, NULL, 1003},
      {"size",        1, NULL, 's'},
      {"density",     1, NULL, 'd'},
      {"clamped",     0, NULL, 1004},
      {"oversample",  1, NULL, 1005},
      {"tileable",    0, NULL, 1006},
      {"fg-alpha",    1, NULL, 1007},
      {"bg-alpha",    1, NULL, 1008},
      NULL,
    };
    c = getopt_long(argc, argv, "hi:o:a:b:c:d:x:y:z:r:e:g:s:t:",
		    long_options, &option_index);
    if (c == -1)
      break;

    switch (c) {

    case 'i':  de_jong_load_image_file(dejong, optarg);       break;
    case 'o':  mode = RENDER; outputFile = optarg;            break;
    case 'a':  de_jong_set(dejong, "a",              optarg); break;
    case 'b':  de_jong_set(dejong, "b",              optarg); break;
    case 'c':  de_jong_set(dejong, "c",              optarg); break;
    case 'd':  de_jong_set(dejong, "d",              optarg); break;
    case 'x':  de_jong_set(dejong, "xoffset",        optarg); break;
    case 'y':  de_jong_set(dejong, "yoffset",        optarg); break;
    case 'z':  de_jong_set(dejong, "zoom",           optarg); break;
    case 'r':  de_jong_set(dejong, "rotation",       optarg); break;
    case 'e':  de_jong_set(dejong, "exposure",       optarg); break;
    case 'g':  de_jong_set(dejong, "gamma",          optarg); break;
    case 's':  de_jong_set(dejong, "size" ,          optarg); break;
    case 't':  de_jong_set(dejong, "target_density", optarg); break;
    case 1000: de_jong_set(dejong, "blur_radius",    optarg); break;
    case 1001: de_jong_set(dejong, "blur_ratio",     optarg); break;
    case 1002: de_jong_set(dejong, "fgcolor",        optarg); break;
    case 1003: de_jong_set(dejong, "bgcolor",        optarg); break;
    case 1004: de_jong_set(dejong, "clamped",        "1");    break;
    case 1005: de_jong_set(dejong, "oversample",     optarg); break;
    case 1006: de_jong_set(dejong, "tileable",       "1");    break;
    case 1007: de_jong_set(dejong, "fgalpha",        optarg); break;
    case 1008: de_jong_set(dejong, "bgalpha",        optarg); break;

    case 'h':
    default:
      usage(argv);
      return 1;
    }
  }

  if (optind < argc) {
    usage(argv);
    return 1;
  }

  switch (mode) {

  case INTERACTIVE:
    gtk_init(&argc, &argv);
    explorer_new(dejong);
    gtk_main();
    break;

  case RENDER:
    render_main(dejong, outputFile);
    break;
  }

  return 0;
}

static void usage(char **argv) {
  printf("Usage: %s [options]\n"
	 "Interactive exploration of the Peter de Jong attractor\n"
	 "\n"
	 "Actions:\n"
	 "  -i, --read FILE       Load all parameters from the tEXt chunk of any\n"
	 "                          .png image file generated by this program.\n"
	 "  -o, --output FILE     Instead of presenting an interactive GUI, render\n"
	 "                          an image with the provided settings and write it\n"
	 "                          in PNG format to FILE.\n"
	 "\n"
	 "Parameters:\n"
	 "  -a VALUE              Set the 'a' parameter\n"
	 "  -b VALUE              Set the 'b' parameter\n"
	 "  -c VALUE              Set the 'c' parameter\n"
	 "  -d VALUE              Set the 'd' parameter\n"
	 "  -x OFFSET             Set the X offest\n"
	 "  -y OFFSET             Set the Y offset\n"
	 "  -z, --zoom ZOOM       Set the zoom factor\n"
         "  -r, --rotation RADS   Set the rotation, in radians\n"
	 "  --blur-radius RADIUS  Set the blur radius\n"
	 "  --blur-ratio RATIO    Set the blur ratio\n"
	 "  --tileable            Generate a tileable image by wrapping at the edges\n"
	 "\n"
	 "Rendering:\n"
	 "  -e, --exposure EXP    Set the image exposure\n"
	 "  -g, --gamma GAMMA     Set the image gamma correction\n"
	 "  --foreground COLOR    Set the foreground color, specified as a color name\n"
	 "                          or in #RRGGBB hexadecimal format\n"
	 "  --background COLOR    Set the background color, specified as a color name\n"
	 "                          or in #RRGGBB hexadecimal format\n"
	 "  --fg-alpha ALPHA      Set the foreground alpha, between 0 (transparent)\n"
	 "                          and 65535 (completely opaque)\n"
	 "  --bg-alpha ALPHA      Set the background alpha, between 0 (transparent)\n"
	 "                          and 65535 (completely opaque)\n"
	 "  --clamped             Clamp the image to the foreground color, rather than\n"
	 "                          allowing more intense pixels to have other values\n"
	 "\n"
	 "Quality:\n"
	 "  -s, --size X[xY]      Set the image size in pixels. If only one value is\n"
	 "                          given, a square image is produced\n"
	 "  --oversample SCALE    Calculate the image at some integer multiple of the\n"
	 "                          output resolution, downsampling when generating the\n"
	 "                          final image. This improves the quality of sharp\n"
	 "                          edges on most images, but will increase memory usage\n"
	 "                          quadratically. Recommended values are between 1\n"
	 "                          (no oversampling) and 4 (heavy oversampling)\n"
	 "  -t, --density DENSITY In noninteractive rendering, set the peak density\n"
	 "                          to stop rendering at. Larger numbers give smoother\n"
	 "                          and more detailed results, but increase running time\n"
	 "                          linearly\n",
	 argv[0]);
}

static void render_main(DeJong *dejong, const char *filename) {
  /* Main function for noninteractive rendering. This renders an image with the
   * current settings until render.current_density reaches target_density. We show helpful
   * progress doodads on stdout while the poor user has to wait.
   */
  GTimeVal start_time, now;
  float elapsed, remaining;
  double iterations;

  g_get_current_time(&start_time);

  while (dejong->current_density < dejong->target_density) {
    de_jong_calculate(dejong, 1000000);

    /* This should be a fairly accurate time estimate, since (asymptotically at least)
     * current_density increases linearly with the number of iterations performed.
     * Elapsed time and time remaining are in seconds.
     */
    g_get_current_time(&now);
    elapsed = ((now.tv_usec - start_time.tv_usec) / 1000000.0 +
	       (now.tv_sec  - start_time.tv_sec ));
    remaining = elapsed * dejong->target_density / dejong->current_density - elapsed;

    /* After each batch of iterations, show the percent completion, number
     * of iterations (in scientific notation), iterations per second,
     * density / target density, and elapsed time / remaining time.
     */
    printf("%6.02f%%   %.3e   %.2e/sec   %6d / %d   %02d:%02d:%02d / %02d:%02d:%02d\n",
	   100.0 * dejong->current_density / dejong->target_density,
	   dejong->iterations, dejong->iterations / elapsed,
	   dejong->current_density, dejong->target_density,
	   ((int)elapsed) / (60*60), (((int)elapsed) / 60) % 60, ((int)elapsed)%60,
	   ((int)remaining) / (60*60), (((int)remaining) / 60) % 60, ((int)remaining)%60);
  }

  printf("Creating image...\n");
  de_jong_save_image_file(dejong, filename);
}

/* The End */
